### ISSUE TITLE
Add a note about the danger of tautologies

### ISSUE THREAD

**Issue by kingthorin** [OWASP/wstg#1028]
**What's the issue?**
SQLi tautologies can lead to undesired outcomes when testing, testers should be very careful how/where they're used.

**How do we solve it?**
Add a note/warning to SQLi section(s) about the danger of `or 1=1` type tautologies.

**Background**
- https://twitter.com/0xTib3rius/status/1623734218302930946
- https://twitter.com/garethheyes/status/1626572052139220993

* https://github.com/search?q=repo%3AOWASP%2Fwstg%20%22or%201%3D1%22&type=code

**Comment by snow-kluster** [comment]
I have fixed this issue and would like someone to check my PR
