### ISSUE TITLE
make pdf easy to locate

### ISSUE THREAD

**Issue by nyck33** [OWASP/wstg#1029]
could find on smartphone, switched to pc and then it's impossible.
some of us like to highlight, annotate, etc so it's more important the web version.
like research papers, have the download pdf in the right column of the web page.
thanks.

**Comment by kingthorin** [comment]
Just hit the “Release Versions” tab on OWASP.org/wstg. Or, grab it from the release in this repo: https://github.com/OWASP/wstg/releases/tag/v4.2
