### ISSUE TITLE
Persian translation (Farsi)

### ISSUE THREAD

**Issue by whoismh11** [OWASP/wstg#1030]
Hello, I am working on the translation of OWASP-WSTG in Persian (Farsi), but it is not finished yet, it is about 50%. I just wanted to let you know that I am working on it and let me know if anyone is willing to collaborate. Thank you.
https://github.com/whoismh11/owasp-wstg-fa

**Comment by kingthorin** [comment]
I'll get this added to the [translation list](https://github.com/OWASP/wstg#translations) shortly:
