### ISSUE TITLE
The "OWASP code review project" reference contains broken links, looks outdated.

### ISSUE THREAD

**Issue by michael-guignard** [OWASP/wstg#1031]
**What's the issue?**
On the [2-Introduction](https://owasp.org/www-project-web-security-testing-guide/latest/2-Introduction/) page, there is a link to [OWASP code review project](https://wiki.owasp.org/index.php/Category:OWASP_Code_Review_Project). Attempting to download the guide using the Quick Links on the right results in a 404.

**How do we solve it?**
This looks like a more recent link, and the download links to the guide also work:
https://owasp.org/www-project-code-review-guide/

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [ ] Assign me, please!

**Comment by snow-kluster** [comment]
> **What's the issue?** On the [2-Introduction](https://owasp.org/www-project-web-security-testing-guide/latest/2-Introduction/) page, there is a link to [OWASP code review project](https://wiki.owasp.org/index.php/Category:OWASP_Code_Review_Project). Attempting to download the guide using the Quick Links on the right results in a 404.
> 
> **How do we solve it?** This looks like a more recent link, and the download links to the guide also work: https://owasp.org/www-project-code-review-guide/
> 
> Would you like to be assigned to this issue? Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
> 
> * [x]  Assign me, please!

**Comment by snow-kluster** [comment]
The lint check workflow fails even though the [link](https://www.it-cisq.org/the-cost-of-poor-software-quality-in-the-us-a-2020-report/ ) is not down also its stopping a bunch of random words calling them incorrect terms like "life cycle " should be written as "lifecycle"

would appreciate your help
