### ISSUE TITLE
GItHub Action Not Creating EPUB

### ISSUE THREAD

**Issue by cmlh** [OWASP/wstg#1056]
https://github.com/OWASP/wstg/actions/runs/4925605704 is not working at the moment.

Issue was reported at https://owasp.slack.com/archives/CJ2QDHLRJ/p1684511522492589

Related to closed https://github.com/OWASP/wstg/issues/729

**Comment by kingthorin** [comment]
@rejahrehim any thoughts on this?

**Comment by kingthorin** [comment]
🤦‍♂️ https://github.com/OWASP/wstg/commit/d8eb8d2619696188c6fb84594bf71403cabca5c6
