### ISSUE TITLE
Shout-out for pytm and threat dragon

### ISSUE THREAD

**Issue by jgadsden** [OWASP/wstg#1059]
**What would you like added?**
Could the existing section on Threat Modeling (section 2.5) be modified with links to [Pythonic Threat Modeling ](https://owasp.org/www-project-pytm/) and [Threat Dragon](https://owasp.org/www-project-threat-dragon/)? These are both OWASP tools and also Lab projects so they should be around reasonably permanently

Would you like to be assigned to this issue?
Check the box if you will submit a PR to add the proposed content. Please read CONTRIBUTING.md.
- [X] Assign me, please!
- [X] Please assign @izar as well as @jgadsden

**Comment by kingthorin** [comment]
Can't assign @izqr unless they comment on the issue.

**Comment by kingthorin** [comment]
- https://owasp.org/www-project-web-security-testing-guide/latest/2-Introduction/README#Threat-Modeling
- https://github.com/OWASP/wstg/tree/master/document/2-Introduction#threat-modeling
