### ISSUE TITLE
E-Book action artifact expired

### ISSUE THREAD

**Issue by dmorawetz** [OWASP/wstg#1103]
**What's the issue?**
The e-book version built at the [action run #3](https://github.com/OWASP/wstg/actions/runs/5194398802) three months ago expired and can't be downloaded anymore. 

**How do we solve it?**
Please run it again and maybe attach the output to the last release. It seems to me that there was no release created at the last run.

Thanks for your awesome work!

**Comment by kingthorin** [comment]
It was just a test run. A real one won't be created/added until the actual next release.

**Comment by kingthorin** [comment]
See https://github.com/OWASP/wstg/releases/tag/20230928

**Comment by dmorawetz** [comment]
It's a really good test run. Looks good on my device, thanks for running it again!
