### ISSUE TITLE
Provide a simplified Chinese translation version for this project

### ISSUE THREAD

**Issue by kmoonn** [OWASP/wstg#1113]
**What would you like added?**
I would like to provide a simplified Chinese translation version for this project. Is it still needed? Has someone already completed or claimed the job? Looking forward to your reply.
Would you like to be assigned to this issue?
Check the box if you will submit a PR to add the proposed content. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by kingthorin** [comment]
Just create a repo and let us know when it's ready then we'll add it to: https://github.com/OWASP/wstg#translations
