### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by ConanNgan** [OWASP/wstg#1137]
**What's the issue?**
Describe the problem and why it should be fixed. Be concise and specific. Reference sections where appropriate.
Ok page 46, it reads "during active testing, a tester begins to use the methodologies described in the follow sections'

**How do we solve it?**
Clearly describe the solution you'd like to see implemented.

It should read  "during active testing, a tester begins to use the methodologies described in the following sections"

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [ ] Assign me, please!

**Comment by kingthorin** [comment]
This error has already been addressed in the current doc.

https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/00-Introduction_and_Objectives/README.md
