### ISSUE TITLE
checklist.json deserves an update

### ISSUE THREAD

**Issue by cydave** [OWASP/wstg#1163]
**What's the issue?**
WSTG-INPV-13 exists twice in [checklist.json](https://github.com/OWASP/wstg/blob/74c9f95d4530781b7c69aab5dde48af15f5d4851/checklists/checklist.json):

+ https://github.com/OWASP/wstg/blob/74c9f95d4530781b7c69aab5dde48af15f5d4851/checklists/checklist.json#L617-L623
+ https://github.com/OWASP/wstg/blob/74c9f95d4530781b7c69aab5dde48af15f5d4851/checklists/checklist.json#L624-L631

Would it maybe make sense to rework the checklist.json [generator](https://github.com/OWASP/wstg/blob/74c9f95d4530781b7c69aab5dde48af15f5d4851/.github/json/scripts/make-json.sh)? :)

**How do we solve it?**
Consider using python to generate an up-to-date checklist.json file instead of using bash magic.
Also, consider excluding removed (or merged) entries from the list.

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [ ] Assign me, please!

**Comment by kingthorin** [comment]
That's a known and accepted issue. Things won't be re-numbered until 5.x because it's technically a breaking change. That's why there are placeholders.

I guess I could look at inserting a fake "Objective" explaining the discrepancy so that it'd show-up in the checklists.

**Comment by cydave** [comment]
Gotcha! Wouldn't it make sense to have separate branches for latest and stable tho?
Maybe that's too big of a restructure, but might be worth considering?
