### ISSUE TITLE
Link to tools that can sniff sessions in "encrypted channel" testing sections

### ISSUE THREAD

**Issue by patrickceg** [OWASP/wstg#138]
**Is your feature request related to a problem? Please describe.**
When going through the pages that mentioned unencrypted channels, there were non-linked mentions of ideas to be able to eavesdrop on the connections (e.g. Wireshark), but those pages did not have the tool linked.

Pages include:

- 4.5.1_Testing_for_Credentials_Transported_over_an_Encrypted_Channel_OTG-AUTHN-001.md
- 4.10.3_Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels_OTG-CRYPST-003.md

**Describe the solution you'd like**

The pages above (and if we find any others talking about sensitive data + non-encrypted communication), should mention tools including Wireshark or intercepting proxies deployable at the router with links.

**Comment by ThunderSon** [comment]
This issue should tackle the discussion of tools and how to use them if possible, to provide proper guidance for people to use that tool with articles and references on it.

**Comment by victoriadrake** [comment]
Is recommending tools in scope for WSTG?

**Comment by kingthorin** [comment]
Yes, testers need to be able to use appropriate tools for testing. While we don't expect any of the suggestions to be exhaustive lists it does make sense to suggest tools that a known to offer a relevant feature or functionality. (Of course testers are always welcome to use whatever they prefer, the guide we have suggestions not requirements...)
