### ISSUE TITLE
Improve consistency for mentions of Black, Grey, White Box Testing

### ISSUE THREAD

**Issue by patrickceg** [OWASP/wstg#139]
**Describe the issue**
I noticed this while going through the content of 4.5.2_Testing_for_Default_Credentials_OTG-AUTHN-002.md. It had this statement that redifined black box testing unnecessarily in a subsection:

> In black box testing the tester knows nothing about the application and its underlying infrastructure. In reality this is often not true, and some information about the application is known.

Since white/grey/black box testing are mentioned in many places in the article, we should use it consistently in the whole document, and not re-explain the terms like in the mention above. Possible fixes are:

- Make a section that explains terms in detail (we'll just focus on black/grey/white box testing here, but if we find other terms that are used a lot, including remediation or automated testing / continuous integration / static analysis, we can place them there as well)
- After the section is in place, we should go through to make sure no section redefines the term out of nowhere. (Instead of copy-pasting the definition, that subsection that wants to reinforce the term can link back to the common definitions area of the document.)

**Comment by victoriadrake** [comment]
I'm coming across this in the introduction as well. Is there a general consensus as to whether Black, White, Grey, should be capitalized or not? Capitalization currently varies.

**Comment by kingthorin** [comment]
If it's a title or name it should use title case.

**Comment by victoriadrake** [comment]
Yes, if the rest of the title also is. I think this is relevant in the course of addressing this issue, so I'll be so bold as to propose a standard with the following example: lowercase and hyphenated (as adjective) by default. Example:

> # A Brief Description of White-Box Testing from Wikipedia

> White-box testing (also known as clear box testing, glass box testing, transparent box testing, and structural testing) is a method of software testing that tests internal structures or workings of an application, as opposed to its functionality (i.e. black-box testing).

> ## A modern view of white-box testing

> A more modern view is that the dichotomy between white-box testing and black-box testing has blurred and is becoming less relevant.

I'm leaning on the [GCC Coding Conventions for spelling](http://gcc.gnu.org/codingconventions.html#Spelling) for the use of the hyphen here. When used as a noun, "a white box" and when used as an adjective, "white-box testing."
