### ISSUE TITLE
Rewrite 4.5.5_Testing_for_Vulnerable_Remember_Password_OTG-AUTHN-005.md

### ISSUE THREAD

**Issue by patrickceg** [OWASP/wstg#140]
**Describe the issue**

While going through the changes to [4.5.5_Testing_for_Vulnerable_Remember_Password_OTG-AUTHN-005.md](https://github.com/OWASP/OWASP-Testing-Guide-v5/blob/master/document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.5_Testing_for_Vulnerable_Remember_Password_OTG-AUTHN-005.md) , I noticed the section seems a bit dated and could use some new information or perhaps a rewrite / merge with other sections.

The weaknesses I found with it are:

- "Additionally some websites will offer custom “remember me” functionality to allow users to persist log ins on a specific client system.":
  * We should add more examples of weak "remember me", like a "remember me" form that actually stores the user's password in the session token or a hidden field
  * We may also want to reference cross site scripting here, since cross site scripting could also steal a "remember me" token in the same way it could steal a live session token
- The article is mixing the browser's "remember me", which is outside the context of the web app, and the web application's "remember me".
  * The article should clearly separate which part of the "remember" is the web app, and which is the browser.
- There is no mention of password managers, which is definitely worth at least a mention. 
  
I'm just going through right now, so I'm not sure of the best way to go about fixing this article. Vulnerable "remember me" definitely blends in with any other article about session tokens, so we'll have to take a look at the session token and this page together to see how we want these to look for consistency.

**Comment by patrickceg** [comment]
@ThunderSon I clarified a bit of the description, although I recommend we give some direction if a new contributor will take it on for Hacktoberfest. Specifically, we should make it clear if we want the section to stay on its own or to be merged into, for example, section [4.5.4](https://github.com/OWASP/OWASP-Testing-Guide-v5/blob/master/document/4_Web_Application_Security_Testing/4.5_Authentication_Testing/4.5.4_Testing_for_Bypassing_Authentication_Schema_OTG-AUTHN-004.md) because messing with a "remember me" is a subset of bypassing authentication schema in some cases.

I'm also unsure what we want to do with the way half the article talks about the browser remembering passwords. In my opinion, insecure use of the web browser is outside the scope of this article (unless the web page's content is actively encouraging the user into bad practices).

**Comment by victoriadrake** [comment]
@patrickceg It looks like we have a point-form list of the things this topic should cover instead. So far we have:

- "remember me" forms/tokens
- web app vs browser password remembering
- password managers
- relation to session tokens
- relation to 4.5.4

Is there anything you'd like to add for a contributor to tackle a rewrite?

**Comment by patrickceg** [comment]
@victoriadrake Two items:

1) For reviewers, verify that after updates, we match ASVS on the same topic https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md

If there is a contradiction, ether we should pick resources to match ASVS, or if ASVS needs updating, file against that project.

2) That ("Remediation: Ensure that no credentials are stored in clear text or are easily retrievable in encoded or encrypted forms in cookies.") is not a remediation step at least by my definition of the term... It looks more like another test you should have. My definition of "remediation" is "steps to limit or undo damage caused by a mistake", in which case the remediation step would be to invalidate all potentially exposed credentials and notify the users.

**Comment by ThunderSon** [comment]
Thanks guys for tackling this 😄 Great point mapping this to the ASVS, as this is one of our v5 targets. I agree to the remediation part. I think based on the written context, the sentence can be judged and fixed.

**Comment by victoriadrake** [comment]
Sounds good @patrickceg. Advice on remediation should be kept to a minimum in the WSTG, as it's in scope for other OWASP projects but not so much for this testing guide (see [article template explanation](https://github.com/OWASP/wstg/blob/master/template/999.2_Template_Explanation_OTG-FOO-002.md)).

@ThunderSon I'm not sure which sentence you're referring to.

Opening up this issue for a rewrite - new contributors welcome, of course!
