### ISSUE TITLE
Update 4.5.6 (browser cache) for new browsers and OS

### ISSUE THREAD

**Issue by patrickceg** [OWASP/wstg#141]
**Describe the issue**

https://github.com/OWASP/wstg/tree/master/document/4_Web_Application_Security_Testing/4.5_Authentication_Testing

The article 4.5.6_Testing_for_Browser_Cache_Weaknesses_OTG-AUTHN-006.md in the "Browser Cache" subsection has information dating back to Windows XP which should be updated:

- Windows paths mention the XP paths `C:\Documents and Settings` instead of `C:\Users`
- Nothing about Chromium based browsers
- Nothing about mobile browsers
  - Mobile browser testing may be a challenge and may need extensions / plugins, but it is worth a mention because unprotected data in a mobile browser has a large attack surface, and there are a few sites that give you a completely different experience (and possibly a different security posture) when you're browsing from mobile.

**Comment by kingthorin** [comment]
@patrickceg did you have anything more specific in mind on the mobile browser front?

I can go looking (it isn't something I've dealt with yet), but am glad for anything you (or anyone) had/have in mind.

**Comment by patrickceg** [comment]
> @patrickceg did you have anything more specific in mind on the mobile browser front?

The comment I meant to make is many web pages treat mobile browsers differently, to the point where sites have a "m.mysite.com" versus a "mysite.com" pointing to different front-ends. That said the comment about mobile being different probably applies to many other parts of the article.

For the purposes of cache testing, it would be good to have instructions to check the cache of at least the default browsers on mobile (Chrome for Android and Safari on iOS). I can't find a way to do that for iOS, but for mobile Chrome, these two links may work:

Simulate Mobile Devices with Device Mode in Chrome DevTools https://developers.google.com/web/tools/chrome-devtools/device-mode
+
View Cache Data With Chrome DevTools
 https://developers.google.com/web/tools/chrome-devtools/storage/cache

**Comment by kingthorin** [comment]
Thanks!
