### ISSUE TITLE
Section 2 - Update References and Text for Test Metrics SubSection

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/wstg#172]
As noted in the following [review comment](https://github.com/OWASP/wstg/pull/168#discussion_r322519280), the metrics for doing tests earlier in the pipeline don't align properly and are probably old by now and needs proper updating.

The required changes are the following:
- Identify proper references and links to backup the claims in that section
- Update the section to the most recent data available

**Comment by victoriadrake** [comment]
@ThunderSon We seem to have lost the reference to the comment and section in question. Would you please update this issue?

**Comment by kingthorin** [comment]
I've updated the link. 

Just in case something changes again here's a screencap:
![image](https://user-images.githubusercontent.com/7570458/72536799-f7896980-3848-11ea-8ec2-118d248ef35a.png)

**Comment by victoriadrake** [comment]
Thank you @kingthorin. To pick up the conversation, I'm with @patrickceg on removing the unsupported claim for v4.1. @ThunderSon how do you feel about that?

**Comment by ThunderSon** [comment]
@victoriadrake Onwards! If we feel that this is something we need to re-inject, we can open an issue about it and try researching. I don't see it as a critical thing to be tackled now.
