### ISSUE TITLE
References and inline links need to be updated

### ISSUE THREAD

**Issue by rejahrehim** [OWASP/wstg#180]
References and inline links throughout the documents need to be updated, as there are many old/outdated links. We have to ensure that each link provided in the reference section fits the topic discussed. 

Also, it would be better to have HTTPS URLs.

**Comment by brainlulz** [comment]
Should this issue be splitted by chapters ?

**Comment by victoriadrake** [comment]
I believe this was partially closed in #182. I'm going to open a specific issues for the remaining work.

**Comment by victoriadrake** [comment]
I've broken out the remaining work into issues:

#275, #276, #277, #278, #279, #280, #281, #282, #283, #284, #285, #286, #287, #288, #289, #290, #291, #292, #293, #295, #296, #297, #298, #299, #300, #301, #302, #303, #304, #305, #306, #307, #308, #309, #310, #311, #312

Also there's a new issue template for reporting broken links.
