### ISSUE TITLE
Improve contribution guidance

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#237]
Improve CONTRIBUTING.md and style guide.

* Clarify and consolidate contribution instructions and writing style guidelines
* Cement article format

**Comment by victoriadrake** [comment]
@ThunderSon Please assign me and add any specific goals that come to mind! Thanks!

**Comment by ThunderSon** [comment]
Thank you for tackling this!
My main need/requirement for this it for it to be welcoming, descriptive, in a way to set the tone for the WSTG. New content will follow it, and old content will be updated accordingly. 😄
