### ISSUE TITLE
Improve sections' front page consistency

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#243]
**What's the issue?**

Consistency currently varies for section pages, such as 4.5 and 4.8. Some section pages have a table of contents while others have a lengthy page giving a summary and other information on the general topic and test cases. In particular I noticed [4.11 Business Logic Testing], which gives a summary of each test (violating DRY principle) and even lists Tools. I'd like to see these pages made more consistent.

**How do we solve it?**
Come to an agreement on the format for section pages, to be included in the project style guide.

Would you like to be assigned to this issue?
_Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md._
- [x] Assign me, please!

**Comment by victoriadrake** [comment]
As mentioned in #224, my vote is for section front pages (README.md of each section folder) to be a simple table of contents listing, without other text.

As is the case with the Format String article issue, that section's front page presents categories for the articles it contains that are unhelpful, and limits the development of the articles themselves. It's also just more text to keep updated, without making an actual contribution to the test scenarios.

**Comment by kingthorin** [comment]
I'm good with shortening/simplifying.  

As things are trimmed and brought into conformance we should consider if any of the intro or summary text should be moved into the actual section(s).

**Comment by ThunderSon** [comment]
Definitely. Let's make the `4` chapter, where every section (`4.x`) goes to drill down attacks, become more so of a ToC of the current things to be discussed. That'll give the readers a better way to access content. Is this what we're looking at?

**Comment by ThunderSon** [comment]
@victoriadrake @kingthorin does my last comment properly tackle the issue raised?

**Comment by kingthorin** [comment]
I think so.

**Comment by victoriadrake** [comment]
So we’re in agreement to remove the intro text from READMEs, turn them into TOC lists instead, and where appropriate move the intro text into the section.

**Comment by kingthorin** [comment]
Yes, from my point of view.
