### ISSUE TITLE
Minor release v4.1

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#249]
**What would you like to happen?**

This issue continues a discussion around making a minor release, [project `v4.1`](https://github.com/OWASP/wstg/projects/1), that began in #248.
This intermediate version would serve as a post-migration stable release, to be served at `https://owasp.org/www-project-web-security-testing-guide/v4.1/`.

TODOs and suggestees so far:

- [x] Specify which test cases will be added or need modifying (@ThunderSon) [This was done in the shared spreadsheet.]
- [x] Add notice of intermediate version in the intro, and that v5 is upcoming (@kingthorin) [Done in OWASP/wstg#251]
- ~~Write up standards for minor releases (@victoriadrake)~~ Deemed unnecessary per chat

**Comment by kingthorin** [comment]
Thanks for setting this up. I’ll try to tackle my bullet this weekend.

Re: URL, don’t we want: https://www2.owasp.org/www-project-web-security-testing-guide/wstg/v4.1/ ? (I may have misunderstood something along the way.)

**Comment by victoriadrake** [comment]
Oh, no, I’m the one that missed it. Though now that I look at it, it does look redundant.

For now I’ll say either is fine, and it will probably come down to how the files are organized in the repo, and how @ThunderSon imagines a latest-version-redirect to take place.

**Comment by kingthorin** [comment]
Okay. 

I agree it looks redundant, I just figured structurally it'd have to be a layer deeper than the project 'about' type content.

**Comment by ThunderSon** [comment]
For the v5 issues, I guess me and Rick should finalize in the coming week the sheet? Stay tuned 😄 
Yeah, let's drop the `wstg` bit. We're good without it. This provides an opportunity.
The default page holds the project's book straight up, and directly loads the tests? I doubt that would be doable in the `www` repo. @victoriadrake what do you think we can do to make this look the best?
And should we be worried about SEO with the versioning? Duplicate content.

**Comment by victoriadrake** [comment]
@ThunderSon regarding duplicate content: see [Google’s breakdown](https://support.google.com/webmasters/answer/66359?hl=en). It may help to provide links to the current version on the page.

I’ve combed the [Jekyll docs](https://jekyllrb.com/docs/pages) and it seems that the page structure is really up to us. We’ll just have to ensure that the site theme (www—site-theme) supports it. I have some ideas about how to achieve what we want but I’m interested to see what @rejahrehim has in mind.

@kingthorin This may be helpful: the [Django documentation](https://docs.djangoproject.com/en/2.1/) has set a precedent we can follow. They have different banner treatments for old, current (no banner), and development doc versions.

**Comment by kingthorin** [comment]
Both TODOs done, closing.
