### ISSUE TITLE
Add reviewer's guide

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#250]
**What's the issue?**
CONTRIBUTING.md does not cover guidance for reviewers.

**How do we solve it?**
Add guidance for editorial and technical reviews.

**Comment by ThunderSon** [comment]
Let's create a new file for this. Maybe `REVIEWERS.md`? I'd like to keep those 2 separated. 😄

**Comment by victoriadrake** [comment]
I'm going to include it in CONTRIBUTING.md since "REVIEWERS.md" isn't one of the [community health files](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file#supported-file-types) that is surfaced appropriately on GitHub.

**Comment by ThunderSon** [comment]
Doesn't hurt. The way you re-wrote the contributing guide is nice and enough
