### ISSUE TITLE
Add testing for authorization bypass via X-Original-URL and X-Rewrite-URL request headers

### ISSUE THREAD

**Issue by righettod** [OWASP/wstg#258]
**What would you like added?**

Add information into the section about testing authorization that show how to test if the target site support *X-Original-URL* or *X-Rewrite-URL* request headers and try to leverage them to bypass the authorization check.

This [source](https://portswigger.net/web-security/access-control) will be used as support and mentioned:

![image](https://user-images.githubusercontent.com/1573775/72602465-9e3c3b80-3917-11ea-906c-3b7065b222c7.png)

Would you like to be assigned to this issue?

Check the box if you will submit a PR to add the proposed content. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by righettod** [comment]
Are you agree if I add a new section in this [page](https://github.com/owasp/wstg/blob/master/document/4_Web_Application_Security_Testing/4.6_Authorization_Testing/4.6.2_Testing_for_Bypassing_Authorization_Schema_OTG-AUTHZ-002.md) named *Testing for X-Original-URL or X-Rewrite-URL request headers supports* ?

**Comment by kingthorin** [comment]
That seems fine to me.

**Comment by ThunderSon** [comment]
@righettod Thanks for tackling this! It's great to have you on here.
I can see you adding a point or two in the summary, and creating a section maybe like:
`Testing for Special Request Header Redirection`? @kingthorin what do you think?

**Comment by kingthorin** [comment]
How about `Testing for Special Request Header Handling`? In case it isn't a redirect and is simply internal handling of the header value, or if there are other scenarios added later (like X-Forwarded-For etc).

**Comment by ThunderSon** [comment]
Works for me. @righettod your acceptance is required 😄 
`Testing for Special Request Header Handling`

**Comment by righettod** [comment]
It's a very good proposal for `Testing for Special Request Header Handling` and, thanks a lot for that, because it allow to extend this section later with future headers for this kind of testing...

I will initiate it with *X-Original-URL* or *X-Rewrite-URL*.

I will deliver a initial PR quickly (I like to be exposed one time again to the deep/massive review of @ThunderSon, it will remind me somes memories on CS project).

**Comment by ThunderSon** [comment]
Hahaha let's go for it! Waiting for that PR 😄

**Comment by kingthorin** [comment]
Assigning myself to investigate and write about other possabilities as mentioned earlier.

**Comment by righettod** [comment]
Feel free to ask in case of need regarding this topic 😃

**Comment by kingthorin** [comment]
Thanks @righettod !

**Comment by kingthorin** [comment]
On it 👍
