### ISSUE TITLE
Remove text about commenting best practices 

### ISSUE THREAD

**Issue by RiieCco** [OWASP/wstg#263]
**What's the issue?**
In the file "4.3.2_Test_Application_Platform_Configuration_OTG-CONFIG-002.md"
i find the following line in chapter *Comment Review*

```
It is very common, and even recommended, for programmers to 
include detailed comments on their source code in order to allow 
for other programmers to better understand why a given decision 
was taken in coding a given function.
```

From the software development books focussed on QA this is contradictive to the best practices described there. The code evolves over time and comments are mostly 
not changed when the code is updated. This ultimately leads to comments that do not reflect the code and that becomes confusing. The code should be self explanatory.

From the book clean code chapter 4 comments :
```
The proper use of comments is to compensate for our failure to express
ourself in code. Note that I used the word failure. I meant it. Comments are 
always failures. We must have them because we cannot always figure out 
how to express ourselves without them, but their use is not a cause for celebration. 
```

**How do we solve it?**
Remove the line of about the comments and simply continue with the part about
sensitive information being displayed in the HTML/Javscript source by
means of revealing comments.

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [X] Assign me, please!

**Comment by RiieCco** [comment]
With no discussion on this ticket can i make the assumption everybody agrees and create a PR? :-)

**Comment by kingthorin** [comment]
I agree, please proceed :grin:

**Comment by RiieCco** [comment]
Awesome thanks!  ^^
