### ISSUE TITLE
Develop Testing for Horizontal Bypassing Authorization Schema 

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#265]
**What would you like added?**

Further develop [Testing for Horizontal Bypassing Authorization Schema](https://github.com/OWASP/wstg/blob/master/Testing_for_Horizontal_Bypassing_Authorization_Schema_WSTG-AUTHZ-002.md) and ensure it meets the [article standard](https://github.com/OWASP/wstg/blob/master/template/999-Foo_Testing/2-Template_Explanation.md).

**Comment by kingthorin** [comment]
As discussed elsewhere this document should probably be merged into `4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md`

**Comment by DomKoe** [comment]
I would like to be assigned to this.

**Comment by kingthorin** [comment]
@DomKoe are you going to be able to tackle this?

**Comment by DomKoe** [comment]
This is also tackled in #467  We can also again put this into separate PRs once #467 was reviewed.
