### ISSUE TITLE
Develop Testing for Vertical Bypassing Authorization Schema

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#266]
**What would you like added?**

Further develop [Testing for Vertical Bypassing Authorization Schema](https://github.com/OWASP/wstg/blob/master/Testing_for_Vertical_Bypassing_Authorization_Schema_WSTG-AUTHZ-00X.md) and ensure it meets the [article standard](https://github.com/OWASP/wstg/blob/master/template/999.2_Template_Explanation_WSTG-FOO-002.md).

**Comment by DomKoe** [comment]
I am not sure what document is referred here, as the link is broken. When this is regarding vertical privilege escalation, I can work on this.

**Comment by victoriadrake** [comment]
Updated links. Thank you @DomKoe, I will assign you.

**Comment by DomKoe** [comment]
Do you want me to remodel the testing example to close this issue, or what do you have in mind?

**Comment by ThunderSon** [comment]
You have done a great job. I will be adding a PR to just fix something minor. Another issue will be opened to give it a nice ID, I guess that'll be postponed a bit till we agree on the versioning that we'll be following from now on. Thanks @DomKoe !
