### ISSUE TITLE
Find a place for Testing_for_APIs.md

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#267]
**What's the issue?**

The document [Testing_for_APIs.md](https://github.com/OWASP/wstg/blob/master/Testing_for_APIs.md) has no section but is otherwise prepared to be included in a new minor release.
API testing should be integrated inside of the pre-existing tests where it fits.

**Comment by ThunderSon** [comment]
Will be tackled in the above mentioned issue.
