### ISSUE TITLE
Add OAuth Testing (OTG-AUTHN)

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#268]
**What would you like added?**
Add an article on testing Oauth. Ensure it follows the [article standard](https://github.com/OWASP/wstg/blob/master/template/999.2_Template_Explanation_WSTG-FOO-002.md).

**Comment by DomKoe** [comment]
@victoriadrake link is broken, so I leave this one here, I believe it is the correct one atm.
**https://github.com/OWASP/wstg/blob/master/template/999.2_Template_Explanation_WSTG-FOO-002.md**

**Comment by kingthorin** [comment]
Fixed. Tickets were opened before the OTG > WSTG change

**Comment by ThunderSon** [comment]
Thanks to @garethventon, provided me with the following link to identify prevention mechanisms. This link can help us write out the tests for this testing scenario:
[Facebook OAuth Framework Vulnerability](https://www.amolbaikar.com/facebook-oauth-framework-vulnerability/)

**Comment by hazanasec** [comment]
I'm happy to begin some work on this

**Comment by kingthorin** [comment]
@hazanasec are you going to be able to tackle this?

**Comment by hazanasec** [comment]
@kingthorin I'm about half way through, was slowed down by personal things

**Comment by kingthorin** [comment]
No worries, was just checking in. Life happens 👍

**Comment by hazcod** [comment]
For reference, the IETF described a set of security practices around OAuth: https://tools.ietf.org/html/draft-ietf-oauth-security-topics-16

**Comment by ThunderSon** [comment]
Mhm, I provided @hazanasec with that and other guidance links. I believe he has something in store for us, just busy I guess with life.
@hazcod Are you interested in helping with this? :)

@hazanasec would you be able to open up a draft PR so maybe we can chime in on it and push it?

**Comment by hazcod** [comment]
I can review or chime in, but in my opinion I haven't done enough oauth security testing to really author it.

**Comment by kingthorin** [comment]
@hazanasec any news?

**Comment by DotDotSlashRepo** [comment]
assign me please.

**Comment by kingthorin** [comment]
Done!

Template info here:: https://github.com/OWASP/wstg/tree/master/template
Style info here: https://github.com/OWASP/wstg/blob/master/style_guide.md

**Comment by ThunderSon** [comment]
This is one of the bigger issues to handle, so feel free to open a draft PR, reach out to us whenever you need for support with work, or anything you might need. Thanks for taking this on!

**Comment by alcastronic** [comment]
Thanks for assigning me @kingthorin & @ThunderSon.

I have started working on this, and pushed an early concept to my repo [05-Testing_for_OAuth_Weaknesses.md](https://github.com/alcastronic/wstg/blob/new-268/document/4-Web_Application_Security_Testing/05-Authorization_Testing/05-Testing_for_OAuth_Weaknesses.md).  I'd like to "move" the OAuth Guide to 05_Authorization_Testing since OAuth is more about authorization.

It would be nice if someone could have a look at it and give some feedback.     

As this can become a rather long guide. Would it make sense to split it in several chapters? 

For example: 
- 05-Testing_for_OAuth_IdP_Weaknesses.md
- 06-Testing_for_OAuth_Client_Weaknesses.md
- 07-Testing_for_OAuth_Ressource_Weaknesses.md

**Comment by kingthorin** [comment]
FYI, I'm not ignoring this, but don't anticipate having time to review or put serious thought into it until the weekend or maybe even early next week.

**Comment by alcastronic** [comment]
Just leaving a message here that I'm still working on this and this is not lost.   
Will clean up what is there till now and make a PR with it.

**Comment by kingthorin** [comment]
Thanks!

**Comment by alcastronic** [comment]
@ThunderSon & @kingthorin Happy New Year 🥳 I have created a PR with the content already available. 

According to what we have discussed I splitted the OAuth testing in three chapters, so far.  I have also ensured to use the correct terminology for OAuth and changed IdP (Identity Provider) which is only used in the Open ID Connect extension to AS (Authorization Server).

Please feel free to add any suggestions.

**Comment by ThunderSon** [comment]
@alcastronic thank you for staying on top of this! That looks like some heavy work. I'll try to tackle this ASAP. Bit of a heavy period.

Happy new year to yourself as well!

**Comment by victoriadrake** [comment]
Closed in #820  and #839
