### ISSUE TITLE
Add Self DOM-Based Cross-Site Scripting Testing

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#269]
**What would you like added?**

Add an article for Self DOM-Based Cross-Site Scripting Testing and ensure it meets the [article standards](https://github.com/OWASP/wstg/blob/master/template/999.2_Template_Explanation_WSTG-FOO-002.md).

Refer to: https://hackerone.com/reports/406587

**Comment by JulienRouse** [comment]
@victoriadrake the link for article standard goes to a 404, do you mean to link to this page https://github.com/OWASP/wstg/blob/master/template/999.2_Template_Explanation_WSTG-FOO-002.md?

**Comment by kingthorin** [comment]
Yes and fixed :+1:

**Comment by DomKoe** [comment]
I would like to be assigned to this.

**Comment by Magii204** [comment]
I would like to work on this.

**Comment by Shivakumar14** [comment]
Unsubscribe
