### ISSUE TITLE
Update links in Appx.A

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#275]
**What's the issue?**

Some links in this section still use HTTP and should be changed to HTTPS. Two links seem to not resolve.

**How do we solve it?**

Update the appropriate links. The tool [markdown-link-check](https://github.com/tcort/markdown-link-check) may be helpful.

**Comment by rejahrehim** [comment]
**Following links are broken:**

**FILE:** document/Appx.A_Testing_Tools_Resource/Appx.A_Testing_Tools.md
[✖] https://www.kali.org/ → Status: 403
[✖] http://bugtraq-team.com/ → Status: 0

**Comment by ThunderSon** [comment]
@rejahrehim do we still have an issue with kali? I received a positive response. Maybe it's caused by a header that gets automatically 403ed?

**Comment by kingthorin** [comment]
www.kali.org works fine for me.

Perhaps you were behind a corporate proxy that prevents access to 'hacking tools' or something?

**Comment by kingthorin** [comment]
Fixed in https://github.com/OWASP/wstg/pull/318/
