### ISSUE TITLE
Update links in Appx.B

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#276]
**What's the issue?**

Some links in this section still use HTTP and should be changed to HTTPS. Three links seem to not resolve.

**How do we solve it?**

Update the appropriate links. The tool [markdown-link-check](https://github.com/tcort/markdown-link-check) may be helpful.

**Comment by rejahrehim** [comment]
**Following links are broken:**

**FILE:**document/Appx.B_Suggested_Reading/Appx.B_Suggested_Reading.md

[✖] https://www.nist.gov/sites/default/files/documents/director/planning/report02-3.pdf → Status: 404
[✖] https://www.owasp.org/index.php/Phoenix/Tools → Status: 404
