### ISSUE TITLE
Update OTG IDs to WSTG

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/wstg#320]
Go over the whole document and update all OTG abbreviations to WSTG in order to push forward the mapping across the repository and with other projects.

**Comment by victoriadrake** [comment]
I highly recommend exploring interactive usage of find-and-replace for this issue. Command line options include `sed` and Vim.

**Comment by kingthorin** [comment]
I'm pretty sure it can be done easily in Eclipse or Notepad++

**Comment by N1ghtCrawl3r** [comment]
Hi, I would like to work on this. To be clear, all abbreviations named "OTG" should be changed to "WSTG" in all the documents in this repo. Is that so?

**Comment by kingthorin** [comment]
I haven't search yet myself, but tentatively yes. I can't think of another word that OTG falls within...

**Comment by ThunderSon** [comment]
Yep, that's it. We're talking both file-names, and in the whole repository.
