### ISSUE TITLE
Add content to 4.2.6_Identify_Application_Entry_Points_WSTG-INFO-006

### ISSUE THREAD

**Issue by jeremychoi** [OWASP/wstg#334]
**What would you like added?**

add about taking advantage of OWASP attack surface detector [https://owasp.org/www-project-attack-surface-detector/](https://owasp.org/www-project-attack-surface-detector/) for gray-box testing

Would you like to be assigned to this issue?
Check the box if you will submit a PR to add the proposed content. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by ThunderSon** [comment]
Hi @jeremychoi ! Any updates on this issue?
