### ISSUE TITLE
Add SameSite to cookie attributes

### ISSUE THREAD

**Issue by rbsec** [OWASP/wstg#353]
The [cookie attributes](https://github.com/OWASP/wstg/blob/master/document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.2_Testing_for_Cookies_Attributes_WSTG-SESS-002.md#testing-for-cookie-attribute-vulnerabilities) testing guide doesn't mention `SameSite` which is supported by pretty much everything and is beign set by default in some browsers.

**Comment by ThunderSon** [comment]
Cookie **prefixes** as well. I'd say those are as important as the attributes.
