### ISSUE TITLE
4.3.10 Misspelled Domain Name in Example2 

### ISSUE THREAD

**Issue by pr1malbyt3s** [OWASP/wstg#357]
**What's the issue?**
Numbered item 2 in Example2 - Expired Domain contains misspelled domain name, ictimmotherdomain.com.

**How do we solve it?**
Update spelling. Ensure it meets style requirements.

Would you like to be assigned to this issue?
- [x] Assign me, please!

**Comment by ThunderSon** [comment]
Thank you for identifying that. Please go ahead 😄 You can tackle grammar issues straight up, no need for issues when it comes to simple things like that.

**Comment by pr1malbyt3s** [comment]
@ThunderSon Thanks! Noted for future edits.
