### ISSUE TITLE
4.11.9 Upload of Malicious Files - Error in Example backdoor usage

### ISSUE THREAD

**Issue by Ix76y** [OWASP/wstg#359]
**What's the issue?**
In the **Test Upload of Malicious Files** section, under **WebShell Backdoor** the example php code checks for the parameter `rq`but below the code snippet the example url http://TargetVictimSite.com/WebShell-backdoor.php?cmd=cat+/etc/passwd is given.

**How to solve it?**
In the example url **cmd** should be replaced with **rq**

**Comment by ThunderSon** [comment]
Thanks @Ix76y !
