### ISSUE TITLE
Add WIP procedures to contribution guide

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#363]
**What's the issue?**

We need a way for contributors working on a PR to indicate it’s not yet ready for review. We created a label, but there’s no written usage guidance. 

**How do we solve it?**

Write up the use of the `work_in_progress` label or find a more robust solution. 

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by kingthorin** [comment]
IMHO using draft PRs would be better, however, that does require people to familiarize themselves with the github web ui.

**Comment by victoriadrake** [comment]
@kingthorin You're probably right. It doesn't appear we can change a PR from standard mode to draft mode, though. Should we keep the label as an alternate method? Or would that be confusing?

**Comment by kingthorin** [comment]
Nope that’s a good point, draft from start if possible. Label after the fact otherwise.

😊

**Comment by victoriadrake** [comment]
Doh.

> Anyone with read access to a repository can view and search the repository’s labels. To create, edit, apply, or delete a label, you must have write access to the repository. ([About labels](https://help.github.com/en/github/managing-your-work-on-github/about-labels))

I suppose those with write access can manage it still.

**Comment by kingthorin** [comment]
Well the team can also stay on top of it. We can also add a ‘ready for review’ label. 

I read basically every notification so we can just do our best 🤷‍♂️

**Comment by ThunderSon** [comment]
Don't worry that much about it 😄 Draft PRs should only be used prior. That's the concept behind them. They're a harbor for people to have something to share, but not to be reviewed, prior to the official PR. Once it's official, either you close it and tell the author to fix so much

**Comment by victoriadrake** [comment]
> Well the team can also stay on top of it. We can also add a ‘ready for review’ label.
> 
> I read basically every notification so we can just do our best man_shrugging

Every one! You're a machine! 🤖💨

I'll go with that for guidance. Draft PR preferred, but if you made a standard one and it's not ready, just comment and say so and we'll label it appropriately.

**Comment by kingthorin** [comment]
> Every one! You're a machine!

I was totally NOT trying to imply that 😔

**Comment by kingthorin** [comment]
Pull requests can now be turned into drafts if needed (if that helps here):
https://twitter.com/github/status/1247981718453334019
