### ISSUE TITLE
4.2.3 - Add other common metadata files

### ISSUE THREAD

**Issue by rbsec** [OWASP/wstg#364]
4.2.3 (Review Webserver Metafiles for Information Leakage) currently only really talks about the `robots.txt` file, but there are some other files on the site that can contain interesting information, such as:

- security.txt
- sitemap.xml
- [Various other services](https://en.wikipedia.org/wiki/List_of_/.well-known/_services_offered_by_webservers) in the `.well-known` directory

Some of these are probably less useful that others, but it's probably worth at least mentioning them. There are probably other things I've missed, and also other common files that may be covered elsewhere (such as `crossdomain.xml`)

**Comment by kingthorin** [comment]
https://www.contributejson.org/

**Comment by kingthorin** [comment]
http://humanstxt.org/
