### ISSUE TITLE
Consider consolidating fingerprinting guides (4.2.8 and 4.2.9)

### ISSUE THREAD

**Issue by rbsec** [OWASP/wstg#366]
Reading through the information gathering section, there's a page on fingerprinting [web application frameworks](https://github.com/rbsec/wstg/blob/master/document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.8_Fingerprint_Web_Application_Framework_WSTG-INFO-008.md) which says:

> [*] Please note that this article makes no differentiation between Web Application Frameworks (WAF) and Content Management Systems (CMS). This has been done to make it convenient to fingerprint both of them in one chapter. Furthermore, both categories are referenced as web frameworks.

It talks about both frameworks (CakePHP, Laravel, etc), and also CMS (WordPress), and discusses various methods (headers, meta tags, whatweb, wappalyzer, etc).

The next page is about fingerprinting [web applications](https://github.com/rbsec/wstg/blob/master/document/4_Web_Application_Security_Testing/4.2_Information_Gathering/4.2.9_Fingerprint_Web_Application_WSTG-INFO-009.md), which covers WordPress, and the same techniques (headers, meta tags, whatweb, weppalyzer, etc).

I'm not sure if this is a legacy thing, but it seems like there's a lot of overlap between these two pages, and perhaps they'd be better merged into one? Or if not, the CMS stuff should probably be removed from the first page.

**Comment by ThunderSon** [comment]
Will be considered and added to an uplift milestone later down the line. Thanks!
