### ISSUE TITLE
Add CAPTCHA bypass testing to 4.4.3: Testing for Weak Lock Out Mechanism

### ISSUE THREAD

**Issue by pr1malbyt3s** [OWASP/wstg#374]
**What would you like added?**
Add CAPTCHA bypass test cases to demonstrate risks associated with improper CAPTCHA implementation. 

Would you like to be assigned to this issue?
Check the box if you will submit a PR to add the proposed content. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by kingthorin** [comment]
@pr1malbyt3s are you going to be able to tackle this?

**Comment by pr1malbyt3s** [comment]
@kingthorin Yes- will try to be done between now and end of next week.

**Comment by ThunderSon** [comment]
@kingthorin safe to close?

**Comment by kingthorin** [comment]
Yup, sorry I guess I missed editing the PR with a closing keyword/ref.
