### ISSUE TITLE
Cookie Prefixes 4.7.2

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/wstg#380]
**What would you like added?**
Scenario [4.7.2 Testing for Cookies Attributes](https://github.com/OWASP/wstg/blob/master/document/4_Web_Application_Security_Testing/4.7_Session_Management_Testing/4.7.2_Testing_for_Cookies_Attributes_WSTG-SESS-002.md) is missing Cookie Prefixes

References:
- [Cookies Prefixes MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Cookie_prefixes)
- [Google's Samples](https://googlechrome.github.io/samples/cookie-prefixes/)

**Comment by ThunderSon** [comment]
Should the section title change as well? This is not an attribute per se.

**Comment by kingthorin** [comment]
I'm okay sticking with "attributes"

**Comment by jespunya** [comment]
Can you please assign me this issue please.
