### ISSUE TITLE
Add Review Frontend for Sensitive Data Exposure (WSTG-INFO)

### ISSUE THREAD

**Issue by crazykid95** [OWASP/wstg#450]
**What would you like added?**
Modern web models have separate Frontend with the Backend API, Frontend often expose sensitive information, such as hardcoded Google Private API Key, Google Map API Key in Javascript variables but not restricted or exposing WebPack map files that contains sensitive routes. This section helps people review Frontend at the Information Gathering stage to quickly identify sensitive information leaked from Frontend.

Would you like to be assigned to this issue?
Check the box if you will submit a PR to add the proposed content. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by ThunderSon** [comment]
Interesting. @kingthorin do you think this could be part of [WSTG-INFO-05](https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/01-Information_Gathering/05-Review_Webpage_Comments_and_Metadata_for_Information_Leakage.md)?

**Comment by crazykid95** [comment]
> Interesting. @kingthorin do you think this could be part of [WSTG-INFO-05](https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/01-Information_Gathering/05-Review_Webpage_Comments_and_Metadata_for_Information_Leakage.md)?

Good Ideal @ThunderSon. I will write it as part of WSTG-INFO-05
