### ISSUE TITLE
Terminology Consistency

### ISSUE THREAD

**Issue by kingthorin** [OWASP/wstg#451]
All occurrences of "Open Source" within the document should use title caps.

In agreement with: https://perens.com/2017/09/26/on-usage-of-the-phrase-open-source/

**Comment by kingthorin** [comment]
It seems there are also places where `javascript` &gt; `JavaScript` is still warranted.

**Comment by victoriadrake** [comment]
Just a caution that article intends for the capitalization to apply to: 

> ... any work to which a license compliant with the Open Source Definition could possibly apply.

There may be occurrences in the WSTG where this context is not the case.

JavaScript is a no-brainer.

**Comment by ThunderSon** [comment]
So when open source is used as a descriptive term, it shouldn't be capitalized, no?

**Comment by kingthorin** [comment]
> Just a caution that article intends for the capitalization to apply to:
> 
>     ... any work to which a license compliant with the Open Source Definition could possibly apply.
> 
> There may be occurrences in the WSTG where this context is not the case.

Ya I read and re-read that a number of times when I created this issue, but my interpretation of that statement was that in the majority of cases "Open Source" likely applies. I guess there might be some abstract references which aren't directly about software in which it might not be applicable. But, my take away was that it should be caps more often than not.
