### ISSUE TITLE
Typos in 04-Testing_for_Weak_Encryption.md

### ISSUE THREAD

**Issue by Franccisco** [OWASP/wstg#476]
**What's the issue?**
There are three typos in the [Source Code Review](https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/04-Testing_for_Weak_Encryption.md#source-code-review) section of this file:
1. "encyprtion" instead of "encryption".
2. Two blank spaces instead of one in `secret Key,  private key`.
3. "althorithm" instead of "algorithm"

**How do we solve it?**
Writing them all correctly.

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by kingthorin** [comment]
Thanks for tackling this. If you're going to tackle something essentially immediately and there's little concern of someone else tackling the same task you can just go ahead with a PR without an issue.

Nice work!

**Comment by Franccisco** [comment]
Understood. You're welcome!
