### ISSUE TITLE
Remove Blindelephant Reference

### ISSUE THREAD

**Issue by marevalo10** [OWASP/wstg#481]
**What's the issue?**
In some of the information gathering pages it is refered the Blindelephant software. However, it is not available anymore after following the links and the reference in their page. 

**How do we solve it?**
I think it should not be refered anymore. I found this github but I'm not sure if this is official or not: https://github.com/lokifer/BlindElephant

Would you like to be assigned to this issue?
- [ ] Assign me, please!

**Comment by calabacito** [comment]
The software hasn't been updated in ages but URL is still working.

**Comment by ThunderSon** [comment]
Indeed it is old and no longer supported, and as such will be removed.

**Comment by ThunderSon** [comment]
Indeed it is old and no longer supported, and as such will be removed.

**Comment by kingthorin** [comment]
Looking at http://blindelephant.sourceforge.net, it lists a few similar tools of which it seems WhatWeb is the only thing still alive and kicking.
