### ISSUE TITLE
Summary Chapter in 3.1 Re-Order

### ISSUE THREAD

**Issue by rcorsi** [OWASP/wstg#488]
**What's the issue?**
At start of Ch 3.1, the summary of items is out of order with how the items are present later in the chapter.

**How do we solve it?**
Would like to change the summary so matches the current order of the document.

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [X] Assign me, please!

**Comment by ThunderSon** [comment]
Go ahead! @rcorsi Thanks :)

**Comment by rcorsi** [comment]
Will do. Thank you.

**Comment by rcorsi** [comment]
Thanks for the commit.

**Comment by rcorsi** [comment]
I meant merge.  :-)
