### ISSUE TITLE
repo: Implement 'textlint terminology'

### ISSUE THREAD

**Issue by kingthorin** [OWASP/wstg#494]
https://github.com/sapegin/textlint-rule-terminology

Start with a stripped down version of:
https://github.com/sapegin/textlint-rule-terminology/blob/master/terms.json

Consider:
- [x] ~https://github.com/OWASP/wstg/pull/491~
- [x] ~https://github.com/OWASP/wstg/pull/487~
- [x] https://github.com/OWASP/wstg/pull/477
- [x] https://github.com/OWASP/wstg/pull/468
- [x] https://github.com/OWASP/wstg/pull/431

**Comment by ThunderSon** [comment]
Is this good to close, or are we looking to monitor an additional PR to see how it behaves?

**Comment by kingthorin** [comment]
There's still more to tackle, I'll add some details later today.

**Comment by kingthorin** [comment]
Sorry I never added the details, however I think it's all been addressed as either part of OWASP/wstg#496 and subsequent PRs that have been subject to the action.

**Comment by kingthorin** [comment]
I'm going to close this. If any issues come up with the action just open an issue or hit me up on slack.

**Comment by kingthorin** [comment]
Re-opening so that I don't forget to deal with "client side" and "server side".

Ref: https://twitter.com/owasp_wstg/status/1281245964888608769
