### ISSUE TITLE
Translation to pt-BR

### ISSUE THREAD

**Issue by raphaelhagi** [OWASP/wstg#497]
Hello there,

Me and some other friends just started a new forked repo for a translation for brazilian portuguese. 

https://github.com/raphaelhagi/wstg

We think this translation will be helpful for a bunch of developers and security professionals in our country.

**Comment by kingthorin** [comment]
@raphaelhagi  could you have a look at [GitLocalize](https://gitlocalize.com/) and let me know what you think?

It seems to be used by some large projects. I did some quick tests with it this evening on a temporary repo and it seems like it could help us here.

**Comment by kingthorin** [comment]
There's a two min intro video here that covers the basic workflow: https://www.youtube.com/watch?v=b09LDukIJiU

**Comment by kingthorin** [comment]
Seems interest in this has waned. GitLocalize has been setup for pt-BR. If someone is interested in moderating the pt-BR contributions please let us know.
