### ISSUE TITLE
Simplify sentence structure in Test HTTP Strict Transport Security

### ISSUE THREAD

**Issue by JustAMurph** [OWASP/wstg#509]
**What would you like added?**

The current sentence is a little long winded. Simplify the sentence while leaving the message in tact.

Change:
Testing for the presence of the HSTS header can be done by checking for the existence of the HSTS header in the server's response in an interception proxy, or by using CURL as follows:

To:
The presence of the the HSTS header can be confirmed by examining the server's response through an interception proxy or by using CURL as follows:

Would you like to be assigned to this issue?
Check the box if you will submit a PR to add the proposed content. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by kingthorin** [comment]
You don't need to open a new issue for every little thing. You can bundle up a bunch of changes and just submit a PR. There's no reason this couldn't have been done as part of the other submission.

Unless you're going to be working on it for days/weeks and are worried about conflicts.

**Comment by kingthorin** [comment]
Also you should not use the "Add New Content" issue template for fixes/revisions....

**Comment by JustAMurph** [comment]
Thank you. Will correct these issues in future. 

Didn't expect to do another one at the time of the other submission.

**Comment by kingthorin** [comment]
Alrighty, thanks!
