### ISSUE TITLE
Missing category in list

### ISSUE THREAD

**Issue by LCraddock** [OWASP/wstg#523]
The list of 11 sub-categories of Active Tests only has 10 items.
Information Gathering is missing from the list.

**Comment by kingthorin** [comment]
Issue transferred from www repo to project repo.

**Comment by kingthorin** [comment]
I believe this is the part that @LCraddock is referring to: https://github.com/OWASP/wstg/tree/master/document/4-Web_Application_Security_Testing/00-Introduction_and_Objectives#active-testing
