### ISSUE TITLE
Updates to malicious file upload testing

### ISSUE THREAD

**Issue by rbsec** [OWASP/wstg#532]
**What's the issue?**
Reading through the [malicious file upload testing](https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Test_Upload_of_Malicious_Files.md) guide there are a few issues:

* Broken link to EICAR
* No warning that leaving world accessible web shells is a _really bad idea_.
* Random third party domain used in examples
* No discussion of the different types of zip bombs
* No warning that uploading zip bombs to a target site is a _really bad idea_.

I'm happy to put together a PR to address the above.

**Comment by ThunderSon** [comment]
This was closed in #533
