### ISSUE TITLE
the content of this link is unrelated

### ISSUE THREAD

**Issue by 1160301013** [OWASP/wstg#540]
**What and where?**
Please give the broken URL. Where is the link located?

The bad URL is <http://www.encription.co.uk/downloads/more_advanced_sql_injection.pdf>. It is not broken. But when I clicked it, an unrelated webpage was opened. The URL is in [this article](https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection.html). It is in the Whitepapers part, the second link.     

I find a valid one, which is <https://www.cgisecurity.com/lib/more_advanced_sql_injection.pdf>. It seems that it is safe according
to [virustotal's report](https://www.virustotal.com/gui/url/a8e1d8196bdcd9d45eaecca3a77f25e05120f13386fd3a3b5e60efb121f326af/detection). Is this one your original PDF?

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [ ] Assign me, please!

**Comment by bhaskar-codes-121** [comment]
I can help with this.

**Comment by bhaskar-codes-121** [comment]
@kingthorin Please review. #541
