### ISSUE TITLE
Support for GitHub Codespaces

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/wstg#546]
**What would you like to happen?**

[Codespaces](https://docs.github.com/en/github/developing-online-with-codespaces/about-codespaces) is in limited beta. I'd love to add a configuration to our project as this feature will allow new contributors to quickly and easily get started on issues.

**Comment by ThunderSon** [comment]
I did love the new tool coming out, yet I believe it's gonna be behind a paywall (from the release of it).

I am not sure it's that interesting to add to the project, especially that it might carry with it bugs.
What do you think @kingthorin ?

**Comment by victoriadrake** [comment]
> I am not sure it's that interesting to add to the project, especially that it might carry with it bugs.

Bugs? Can you elaborate?

**Comment by ThunderSon** [comment]
It's in Beta. There are no promises for it to be stable, not contain bugs/issues, and you know things that come along with a Beta release.

**Comment by victoriadrake** [comment]
Oh, I understand. GitHub Codespaces is in beta, however VS Codespaces (formerly Visual Studio Online) itself has been around a while, if that helps to assuage concerns: https://visualstudio.microsoft.com/services/visual-studio-codespaces/

Do you mean you'd prefer to discourage its use? Adding the devcontainer.json settings for codespaces won't introduce any bugs to our repo on their own.
