### ISSUE TITLE
Proposal: C-Fuzz_Vectors reference based

### ISSUE THREAD

**Issue by kingthorin** [OWASP/wstg#556]
Transform the C appendix from a content based appendix to a reference based appendix.

It seems like a waste of space (esp in print) to include appendix C as-is. It will quickly and undoubtedly become outdated or lacking details. I think our readers would be much better served by providing a curated set of references, such as:

- [XssPayload Twitter Feed](https://mobile.twitter.com/XssPayloads)
    - XssPayloads twitter feed is good on it's own. Recently tweeted about 3000 payloads: https://ghostbin.co/paste/qo23j (I'm not entirely sold on including a ref to such a paste)
- [Cross-site scripting (XSS) cheat sheet](https://portswigger.net/web-security/cross-site-scripting/cheat-sheet)
- [AwesomeXSS](https://github.com/s0md3v/AwesomeXSS)
- [Payloads All The Tings](https://github.com/swisskyrepo/PayloadsAllTheThings)
- [Big List of Naughty Strings](https://github.com/minimaxir/big-list-of-naughty-strings)
- [Bo0oM Fuzz List](https://github.com/Bo0oM/fuzz.txt)
- [FuzzDB](https://github.com/fuzzdb-project/fuzzdb)
- [bl4de Dictionaries](https://github.com/bl4de/dictionaries)
- [Open Redirect Payloads](https://github.com/cujanovic/Open-Redirect-Payloads)
- [EdOverflow Bug Bounty Cheat Sheet](https://github.com/EdOverflow/bugbounty-cheatsheet)
- others???
  - [Daniel Miessler - SecLists](https://github.com/danielmiessler/SecLists)

**Comment by ThunderSon** [comment]
I love this. @righettod what do you think about it? :wink: 

I see the risk where links might die out, and it would still be much more resourceful than how it is.
A thing we can do maybe, if we automate grabbing the payloads from specific places, and creating a payload list to be used by fuzzers, unless that's already done, we don't need to re-create it. Yet, that'd be an additional file, not an appendix.

**Comment by righettod** [comment]
Hi, I agree that a list of ref (maintained) is better because this area
evolve quickly and it will be easier to update a ref than a whole content.
A good centralized repo for payloads dictionaries is the SecLists from
Daniel Miessler. It is actively maintained and very useful.

**Comment by righettod** [comment]
Link: https://github.com/danielmiessler/SecLists
