### ISSUE TITLE
Add a Chapter Back Button

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/wstg#562]
**What would you like to happen?**
On every page, add a link to the previous section.
So if I am in a test scenario, I will go back to the full section.
If I am in a specific section, I'll go back to the full chapter content.

I believe this improves the readability of the document on github and on the main website.

**Comment by kingthorin** [comment]
`../` ?

**Comment by ThunderSon** [comment]
Yep, basically.

**Comment by NFavareto** [comment]
Hello, as I'm new to the project, i am becoming familiar with it. I can do thos enhancement ?

**Comment by kingthorin** [comment]
It can likely literally be `../`.

README.md is default on GitHub and we create new defaults as part of the automated web deployment(s).

We just need to decide where/how we want them placed.

**Comment by kingthorin** [comment]
I might even propose that we don't worry about the GitHub experience at all, but just add them on the fly during web deployment. (It'll suck to have to manipulate them for the PDF production.)

However, that means we need to decide on the implementation details and also tweak the deployments for manual triggering after it's been setup and tested locally.
(Also gotta decide if we are going to try to backport or only handle in latest and future releases.)

**Comment by NFavareto** [comment]
Yes, in this moment, i thought of adding something like `[Back to previous section](../)`  in full section and `[Back to previous section](./)` in test scenario to check more quickly the efficient of this improvement.

**Comment by NFavareto** [comment]
Wow, so the intention is to make this doc available on the web? Sensational! How can I give my suggestions?

**Comment by ThunderSon** [comment]
Hello @NFavareto ! Our efforts were put on version 4.1 to make it web accessible.
Web link: https://owasp.org/www-project-web-security-testing-guide/

Decisions on this issue will be from @kingthorin , as he sees things from a better perspective and I am mostly in agreement to anything :yum: 
He's more into "How things will map" between this repository and the web one.

**Comment by NFavareto** [comment]
Hello @ThunderSon ! I agree, I will try to take one of the issues that are aimed at people who are starting to contribute to the project :smile:

**Comment by ThunderSon** [comment]
@NFavareto Thank you for your enthusiasm and the PR you opened! I'd be joyful to review what you contribute later on. You can start with simple tasks such as discussing certain issues that are open already, or create new ones, and from there take it to a PR if need be :smile:

**Comment by kingthorin** [comment]
Do we care if this is actually back (`history.back()` or `history.go(-1)`) vs just another link `../`.

I'm fine with it being just another link and not worrying about people's history, but it's easy to implement either way.

Since it's all markdown based I'm not 100% sure of the effectiveness of:
`[Back](javascript:history.back())` or `[Back](javascript:history.go(-1))`
vs 
`[Back](../)`
across the majority of modern browsers.

**Comment by ThunderSon** [comment]
@victoriadrake @rejahrehim any comments on the proposal of @kingthorin 
I am with making it a `../` because the user is asking to go back through the page, and not the browser history.

The floating part is interesting, yet I am not the best to discuss this :)

**Comment by victoriadrake** [comment]
Thanks for the tag!

I'm not enthused about using `history.back()` for reasons I'm sure y'all can imagine. I'm pretty sure the following will be rendered from Markdown to HTML since since the web site builds with Jekyll:

```md
(Previous page)[../]
```

For example this would take you from `https://owasp.org/www-project-web-security-testing-guide/v41/0-Foreword/` to `https://owasp.org/www-project-web-security-testing-guide/v41/`.

**Comment by kingthorin** [comment]
Yup that does work. (At least it’s does in local testing). I just wanted to offer up options since it’s a back link that actually technically goes forward.

**Comment by victoriadrake** [comment]
Ah, I'm not really worried about that. If we want to make it more clear, we could present it in a breadcrumb format.

**Comment by ThunderSon** [comment]
@kingthorin We are generating the list of files and how they should be organised for the official website. Is there a Jekyll plugin that could help with next and back buttons?
I feel like this could be feasible in a fast way.

**Comment by kingthorin** [comment]
Not on the GitHub approved list. However, just including it along with the front  matter we already prepend isn’t a big deal.

**Comment by ThunderSon** [comment]
Are you discussing the back button, or what I said? Having a next button too would be a really good thing

**Comment by kingthorin** [comment]
Issue is for a back button 😀

Back is simple and non-specific. 
“Next” would have to be highly specific and dynamic. (Ex: for the last scenario of a chapter ‘next’ is the lead-in or index for the following full chapter.)

**Comment by kingthorin** [comment]
@ThunderSon are you happy with how this looks?
![image](https://user-images.githubusercontent.com/7570458/98764015-e8ac0e80-23a8-11eb-9366-5ec48e536138.png)

**Comment by ThunderSon** [comment]
Love it as a concept! This helps people navigate around much easier because the ToC on the right is just too big to be used.

**Comment by victoriadrake** [comment]
Breadcrumbs! Nice.

`>` or `/`? Either works but my Linux head prefers the `/` :grin:

**Comment by kingthorin** [comment]
Breadcrumb is now live in the [/latest](https://owasp.org/www-project-web-security-testing-guide/latest/) deployment.

**Comment by kingthorin** [comment]
I should change it to use a proper css style is `0.8em` too small, should I switch it up to `0.9em` like the sidebar?

**Comment by ThunderSon** [comment]
Nope, looks good to me, makes a difference between other links in the page.
