### ISSUE TITLE
ATHN-01 Can be removed and replaced by the Crypto Tests

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/wstg#563]
**What's the issue?**
ATHN-01 discussed authenticating over TLS, which is basically the requirements put by cryptography to ensure that communication is happening in a private and secure manner.

**How do we solve it?**
Move this test scenario or merge it with another one in the cryptography tests.

I can take care of this, no problem. I'd prefer seeing it being taken care of by someone trying to contribute as it is a bit easy and fun :blush:

**Comment by Mindslave** [comment]
Hi,
is this issue still up for anyone to take? After looking at the discussion on #419 I'm not sure anymore.
If it is I'm looking for a way to make my first contribution to OWASP and this seems like a good point to start.

If the plan is to merge ATHN-01 into CRYP-01, whats going to happen to the other ATHN-XX Numbers? Do they all change accordingly (decrement by one)?

**Comment by kingthorin** [comment]
We're still in a little bit of a [winter lull](https://github.com/OWASP/wstg/issues/687), I believe this one is still up to be tackled. 

For the numbering while we're in the 4.x series of releases there will be a placeholder, once we roll 5.x everything will shift.
- Similar to here: https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/03-Testing_for_HTTP_Verb_Tampering.md
- Aligning with: https://github.com/OWASP/wstg#how-to-reference-wstg-scenarios

**Comment by Mindslave** [comment]
I think I'm gonna give it a shot then, you can assign this issue to me.  
Regarding my last comment "If the plan is to merge ATHN-01 into CRYP-01", CRYP-03 seems more suitable.
