### ISSUE TITLE
GH Actions - Publish only on the main repository

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/wstg#565]
**What's the issue?**
The publishing actions are activated on all repositories.

**How do we solve it?**
Enforce that only on this repository (OWASP/wstg) deploy actions are activated

**Comment by kingthorin** [comment]
This is out of our control (as far as I know). If users want actions disabled on their forks they need to visit the settings page and disable them.

**Comment by ThunderSon** [comment]
Yep, after reading docs it's as such. If we want, we can add a certain flag (If the secret token isn't around, stop it), but I doubt that's really important. Closing it.
