### ISSUE TITLE
ATHZ-01 Directory Traversal Payloads

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/wstg#567]
**What would you like to happen?**
In ATHZ-01, Directory Traversal scenario, there is a lot chit chat and payloads that are possibly outdated, could be improved, etc.

I was going around for payloads for this test, and this section was fantastic:
https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Directory%20Traversal

What do you think would be a nice way to merge things? Should we just reference the payloads, and give advice on how to use and where to identify such vulnerabilities? Would that be a good test scenario?

**Comment by n17h31sm** [comment]
I looked over the current document.  In my opinion we could cut the size of the examples i.e:

1. How do identify vulnerable endpoints ( we can keep it)
2. Mentions the most common examples ( ../../,  External file)
    - Mention it can lead to other vulnerabilities
    - Add the link to PayloadAllTheThings
3. Mention encoding / fuzzing 

If there are no other candidates (new joiners and so on) I would take it.

**Comment by ThunderSon** [comment]
Closed in #662
