### ISSUE TITLE
Fuzzing Improvements

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/wstg#588]
Following #585 I was interested to see that the [OWASP Community fuzzing link](https://owasp.org/www-community/Fuzzing) is really weak.

In addition, through the cleanup, the categories were removed in Appendix C.
Should we look to improve Appendix C, or to make the community link much better and contain techniques and ways to fuzz?

**Comment by ThunderSon** [comment]
After reviewing both parts, I believe both should be reviewed and stay independent from each other as fuzzing as a topic is much wider than what WSTG is concerned with.

For the WSTG, the appendix needs to:

- Describe what is fuzzing in short.
- Describe the need for fuzzing in short.
- Mention fuzzing tools that the tester can use
- Wordlists and references (which are already set as it is now) that can be used.
- Maybe an example using `wfuzz` on a certain input value?

We can have sections for the wordlists at a later stage, I don't see it as a crucial point for now.

**Comment by kingthorin** [comment]
Another potential ref/source: https://github.com/antonio-morales/Fuzzing101

**Comment by ThunderSon** [comment]
I'll tackle this to remove it off of our backlog

**Comment by kingthorin** [comment]
Poke :wink:

**Comment by maheshbasnet089** [comment]
Can i work on this issue ?

**Comment by kingthorin** [comment]
Sure, just make sure you use  https://github.com/OWASP/wstg/issues/588#issuecomment-714486547 as a guideline.

**Comment by maheshbasnet089** [comment]
https://github.com/OWASP/wstg/pull/979/files

here is my pr kingthorin, any things to be updated?

**Comment by maheshbasnet089** [comment]
How long does it take to be published here too sir
https://owasp.org/www-project-web-security-testing-guide/latest/6-Appendix/C-Fuzz_Vectors

**Comment by kingthorin** [comment]
It won't. It should have been added to the existing content, not added as a new page 🤦‍♂️

I'll get it fixed sometime in the next few weeks.

**Comment by maheshbasnet089** [comment]
Ok, thanks.

**Comment by kingthorin** [comment]
It's now live.
