### ISSUE TITLE
Add "Objectives": "<Grab objectives>" in JSON checklist

### ISSUE THREAD

**Issue by rejahrehim** [OWASP/wstg#589]
Need to update the current JSON checklist with `Objectives`

- Objective can be updated once we have an objective section in each test case.

**Comment by ThunderSon** [comment]
@rejahrehim Let's start with objectives, and with that the first step would be to identify which scenarios don't have objectives, add them, and then make sure everything is following the same format that gets put into the JSON file.
What would you recommend to go on with this? I don't mind doing the work modifying and adding them objectives for missing ones.

**Comment by rejahrehim** [comment]
@ThunderSon  I will create a list of TCs without objectives and share it here.

**Comment by ThunderSon** [comment]
@rejahrehim my comment was mainly to say "Let's automate that", so no need to create a list by hand, if that's what you're after :smile: 
That way we are kind of doing a TDD approach with a live test case.
