### ISSUE TITLE
Local Tools Don't Load Configuration Files

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/wstg#607]
**What's the issue?**
Local linting no longer takes into account the configurations set in the project (and any other extension we tell the users to set up locally).

**How do we solve it?**
Add a configuration for vscode to locate the config files, or revert back the change.

**Comment by kingthorin** [comment]
It doesn't seem practical to try to maintain settings files for all possible editors/add-ons that people may choose to use.

That being said this is likely a problem for the Codespaces setup as well.

I'll investigate pointing markdownlint at a config file in a custom location.

**Comment by kingthorin** [comment]
https://github.com/DavidAnson/vscode-markdownlint/issues/132
