### ISSUE TITLE
Credits for 4.2

### ISSUE THREAD

**Issue by kingthorin** [OWASP/wstg#632]
Please reply below letting us know how you'd like to be listed in the credits: https://github.com/OWASP/wstg/blob/master/document/1-Frontispiece/README.md

Anyone who hasn't replied by 2020-11-28 will be listed simply by their GitHub username, or full name if listed.

## New Authors
- [x] @DomKoe (https://github.com/OWASP/wstg/issues/632#issuecomment-733124250)
- [x] @rishuranjanofficial (https://github.com/OWASP/wstg/issues/632#issuecomment-731591200)
- [x] @pr1malbyt3s 
- [x] @rbsec 
- [x] @AlessiaMichelaDiCampi (https://github.com/OWASP/wstg/issues/632#issuecomment-731593503)
- [x] @eleumasc (https://github.com/OWASP/wstg/issues/632#issuecomment-731598169)
- [x] @scalzava (https://github.com/OWASP/wstg/issues/632#issuecomment-731592729)
- [x] @1Oreo (https://github.com/OWASP/wstg/issues/632#issuecomment-731589227)

## New Editors
- [x] @frozenSolid 
- [x] @Franccisco 
- [x] @marevalo10
- [x] @imthomas93 (https://github.com/OWASP/wstg/issues/632#issuecomment-732024353)
- [x] @Abhi-M (https://github.com/OWASP/wstg/issues/632#issuecomment-731704924)
- [x] @Hsiang-Chih (https://github.com/OWASP/wstg/issues/632#issuecomment-731703727)
- [x] @JustAMurph (https://github.com/OWASP/wstg/issues/632#issuecomment-731589827)
- [x] @najum98 (https://github.com/OWASP/wstg/issues/632#issuecomment-731602135)
- [x] @n17h31sm (https://github.com/OWASP/wstg/issues/632#issuecomment-731633614)

Based on reviewing: https://github.com/OWASP/wstg/pulls?page=1&q=is%3Apr+created%3A%3E2020-04-21+is%3Aclosed

**Comment by najum98** [comment]
I would like to be listed with my Twitter handle i.e Najum98.

**Comment by 1Oreo** [comment]
I'd like to be listed with my name "Or Asaf", Thanks.

**Comment by JustAMurph** [comment]
I'd like to be listed with my name. Eoin Murphy (@JustAMurph). Please and thank you.

**Comment by rishuranjanofficial** [comment]
Thank you.

I would like to be listed with my name.

*Rishu Ranjan* (https://github.com/rishuranjanofficial)

**Comment by scalzava** [comment]
Please use my full name for me: Stefano Calzavara. Thanks,
--
Stefano

Il sab 21 nov 2020, 15:35 kingthorin <notifications@github.com> ha scritto:

**Comment by AlessiaMichelaDiCampi** [comment]
Hi! it's ok the name of my github account, thanks
    Il sabato 21 novembre 2020, 16:18:01 CET, Stefano Calzavara <notifications@github.com> ha scritto:  
 
 

Please use my full name for me: Stefano Calzavara. Thanks,
--
Stefano

Il sab 21 nov 2020, 15:35 kingthorin <notifications@github.com> ha scritto:

**Comment by kingthorin** [comment]
> I would like to be listed with my Twitter handle i.e Najum98.

Heya, glad to list you as “Najum98” or “@Najum98” but please be aware it will just be a text reference like the others (not linked).

**Comment by eleumasc** [comment]
Hi, please use my full name: Samuele Casarin. Thank you in advance!

**Comment by najum98** [comment]
> 
> 
> > I would like to be listed with my Twitter handle i.e Najum98.
> 
> Heya, glad to list you as “Najum98” or “`@Najum98`” but please be aware it will just be a text reference like the others (not linked).

Oh then kindly keep it as, "Najam Ul Saqib" if it's just plain text

**Comment by n17h31sm** [comment]
Hi, I would like to be listed with my full name "Nikoleta Misheva".

**Comment by Hsiang-Chih** [comment]
I'd like to be listed with my name 

Hsiang-Chih Hsu

**Comment by Abhi-M** [comment]
Thanks for asking and for including the name. Please use my full name:
`Abhi M Balakrishnan`

**Comment by imthomas93** [comment]
Hello!

I would like to be listed with my name - Thomas Lim (@imthomas93). Thank you!

Thomas
________________________________

**Comment by najum98** [comment]
I cant see my name mentioned at https://github.com/OWASP/wstg/blob/master/document/1-Frontispiece/README.md . When will it be done?

**Comment by ThunderSon** [comment]
When 4.2 gets released, as the issue states. Please keep this issue for its purposes as there are 19 people in this thread.

**Comment by DomKoe** [comment]
Hello,
thank you as well for asking. I would like to be listed with: Dominik Koehler
Thank you very much and stay healthy you all!
