### ISSUE TITLE
Add language:Simplified Chinese

### ISSUE THREAD

**Issue by Alex-null** [OWASP/wstg#648]
I am willing to moderate GitLocalize efforts for Simplified Chinese.

**Comment by kingthorin** [comment]
I've just added `Chinese [zh-CN]`  for translation. I was not able to see your GitHub account to assign you as moderator. Let us know once you've logged in.

**Comment by Alex-null** [comment]
I've logged in.Thanks.

**Comment by kingthorin** [comment]
Thanks, once I can see you I'll get you setup as the moderator.

**Comment by kingthorin** [comment]
All set, needed to use a leading capital ⭐
