### ISSUE TITLE
consider adding a package-lock.json or yarn.lock

### ISSUE THREAD

**Issue by efx** [OWASP/wstg#651]
**What's the issue?**
The project contains a `package.json` but no `package-lock.json` or `yarn.lock`. Versioning the `package.json` but not a lock file presents 2 problems:
- the dependency version may drift which can make troubleshooting overly complex
- contributors who run `yarn install` or `npm install` will generate 2 different lock files. This will create unnecessary changes in the working directory.

**How do we solve it?**
We first should decide on the kind of locking mechanism. I would suggest sticking to npm's defaults for simplicity. (`package-lock.json`).
Then we would want to:
- version that file
- ignore the other lockfile in `.gitignore`
- document the decision in contributing 

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by kingthorin** [comment]
There's nothing to lock, look at the content of the file. It defines our project and some scripts we run in GitHub actions.

**Comment by kingthorin** [comment]
I'm going to leave this open because we should in fact add the two outlined lock files to `.gitignore` so that people who run and install when there's nothing to install don't end-up PRing garbage files 😀
