### ISSUE TITLE
Link to a deprecated software 

### ISSUE THREAD

**Issue by yuraloginoff** [OWASP/wstg#680]
**What's the issue?**
Here [WSTG-INFO-01](https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/01-Conduct_Search_Engine_Discovery_Reconnaissance_for_Information_Leakage.html) is a link to the deprecated tool "Bishop Fox’s Google Hacking Diggity Project." [Proof](https://twitter.com/bishopfox/status/1336354792822587393).

**How do we solve it?**
Remove the whole sentence "Databases for other search engines, such as Bing and Shodan, are available from resources such as Bishop Fox’s Google Hacking Diggity Project."  ??

**Comment by kingthorin** [comment]
Thanks!
