### ISSUE TITLE
Mitigate Clickjacking by Content-Security-Policy

### ISSUE THREAD

**Issue by kousha1999** [OWASP/wstg#701]
**What's the issue?**
There is a almost new solution to avoid Clickjacking with `Content-Security-Policy` header.
I'll PR it ASAP. I'm not fluent in English. Can someone check grammar (also technically) please?

- [X] Assign me, please!

**Comment by kingthorin** [comment]
Keep in mind this guide is about testing not control or countermeasure implementation.

**Comment by manindar-mohan** [comment]
Please assign this to me.
