### ISSUE TITLE
Translation to Persian

### ISSUE THREAD

**Issue by v-zafari** [OWASP/wstg#704]
Hello everybody

We (My team) want to translation wstg to **persian** language 🎅.
please add persian language in GitLocalize.

**Comment by kousha1999** [comment]
I've started this project (Translation to Persian) last month. So i think, it is better to don't bother yourself. I've done 40% of translation. It will be done soon.

**Comment by kingthorin** [comment]
Persian [fa] has now been added to GitLocalize.

Please let us know who will moderate submissions.

**Comment by kousha1999** [comment]
@kingthorin I can moderate this, as i said i already did that in last month some part of it.

**Comment by kingthorin** [comment]
Okay I’ve set you. I’ll be priming the image directories, etc after the 26th. (That doesn’t keep anyone from moving ahead with translation work.)

**Comment by v-zafari** [comment]
That's excellent @kousha1999 
Our team has also done a lot of translations and it is currently under review.
We are waiting for you to put your (40%) translations in GitLocalize to prevent rework.

Regards
Zafari

**Comment by Nima-Dabbaghi** [comment]
Do not bother @v-zafari . In total, 60% of the translation of the book has been completed and will be published soon.

**Comment by v-zafari** [comment]
Thank you for your advice @Nima-Dabbaghi , publishing this book in Persian is good news.
No problem, multiple translations can improve the quality!
Based on your comment (60% progress) and @kousha1999 comment (40% progress), our team seems to be ahead, most of the work is done and it is being finalized.
