### ISSUE TITLE
Broken Link: Man-in-the-middle_attack → Manipulator-in-the-middle_attack

### ISSUE THREAD

**Issue by jespunya** [OWASP/wstg#736]
**What and where?**

FILE:document/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/03-Testing_for_Sensitive_Information_Sent_via_Unencrypted_Channels.md
https://owasp.org/www-community/attacks/Man-in-the-middle_attack → Status: 404

It should be:

https://owasp.org/www-community/attacks/Manipulator-in-the-middle_attack

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by kingthorin** [comment]
It was broken here: https://github.com/OWASP/www-community/pull/400
