### ISSUE TITLE
Update password reset testing guidance

### ISSUE THREAD

**Issue by rbsec** [OWASP/wstg#742]
The current [password reset testing guidance](https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/04-Authentication_Testing/09-Testing_for_Weak_Password_Change_or_Reset_Functionalities.md) is missing quite a few areas, such as any testing of the password reset link, account enumeration and automated attacks.

It also seems a little confusing that it covers both password resets, and password change functionality. They're certainly related - but the things that you would test for in both cases are fairly different. I wonder if it would make more sense to split into two?

I'm happy to throw together a draft PR with a suggested skeleton for the new content, and then to flesh it out once we're happy with that.

- [x] Assign me, please!

**Comment by ThunderSon** [comment]
Would love that, please go ahead. Feel free with what works best for you (skeleton or a draft).

I can clearly say the attack scenarios are a bit different, so they can definitely be split, or even merged into something else (for example user guessing has another test).

**Comment by rbsec** [comment]
The associated PR (#743) is ready for review.
