### ISSUE TITLE
Add Testing for mass assignment / autobinding

### ISSUE THREAD

**Issue by twicedi** [OWASP/wstg#748]
**What would you like added?**
It might be useful to add a specific section dedicated to tests for mass assignment / "autobinding" vulnerabilities. Something very generic is treated inside the [WSTG-BUSL-07](https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/07-Test_Defenses_Against_Application_Misuse.md) in which, among the potential application misuses, there is the possibility to add additional parameters, however I think that a specific section could be considered since this type of issue can affect many frameworks.

Would you like to be assigned to this issue?
- [X] Assign me

**Comment by twicedi** [comment]
Thanks @kingthorin, regarding the categorization, the ASVS put the related requirement [V5.1.2 ("Verify that frameworks protect against mass parameter assignment attacks, or that the application has countermeasures to protect against unsafe parameter assignment, such as marking fields private or similar")](https://github.com/OWASP/ASVS/blob/v4.0.2/4.0/docs_en/OWASP%20Application%20Security%20Verification%20Standard%204.0.2-en.csv) under the "Input Validation" section therefore, to maintain consistency, we can also put it under the "Input Validation Testing" chapter however I believe that it might even fall under other categories.
What do you think about it?

**Comment by ThunderSon** [comment]
It can be mentioned in both. I'd detail it in the INPV section, and referenced in the BUSL section. It was a good catch to begin with, fitting into that section, might as well benefit from your analyses :)
A developer would consider the framework not vulnerable to such a thing based on the assumption that "I am not parsing this, why would it".

If there is disagreement on this, feel free to begin writing the section you have in mind, and things will fall apart as we move this forward. Admin stuff shouldn't hold you back :)

**Comment by twicedi** [comment]
Perfect, thanks @ThunderSon. I begin writing the section and I agree putting it under INPV chapter, referenced under the BUSL chapter. Anyway, if needed, we can always do further evaluations once the section will be completed.

**Comment by twicedi** [comment]
I'm still working on this topic.
