### ISSUE TITLE
Link update for Practical HTTP Host Header Attacks on WSTG-INPV-17 Testing for Host Header Injection

### ISSUE THREAD

**Issue by mrjonstrong** [OWASP/wstg#771]
Page 
https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/17-Testing_for_Host_Header_Injection

In 'References' at the bottom of the page the last bullet point 'Practical HTTP Host Header Attacks'

Currently points to: https://www.skeletonscribe.net/2013/05/practical-http-host-header-attacks.html
Should point to: https://portswigger.net/web-security/host-header

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by kingthorin** [comment]
Why should it point to portswigger? It’s skeletonscribe’s original work.

**Comment by mrjonstrong** [comment]
Good question @kingthorin 

I read and followed the link in the first paragraph of his post ('Update from 2020) which linked to the portswigger lab. Having read both I thought that the updated page from 2020 might be better to point to than the original post he preserved from 2013.

![Screenshot 2021-07-16 at 14 45 19](https://user-images.githubusercontent.com/42520909/125958532-16390501-dc3d-4ebb-bff0-a231856ccdd6.png)

Does that answer your question?

**Comment by kingthorin** [comment]
Fair enough
