### ISSUE TITLE
DOM Based Self-XSS Needs Relocation

### ISSUE THREAD

**Issue by kingthorin** [OWASP/wstg#779]
~~Objectives need to be added to https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/07-Input_Validation_Testing/20-Testing_for_Self_DOM_Based_Cross_Site_Scripting.md~~

This scenario should be moved to 4.11.1.1 kind of like the specific "flavors" of SQLi.

**Comment by victoriadrake** [comment]
Does this satisfy https://github.com/OWASP/wstg/issues/591?

**Comment by kingthorin** [comment]
Nope. that's separate.

**Comment by kingthorin** [comment]
https://github.com/OWASP/wstg/pull/782
