### ISSUE TITLE
Add CDN bypasses and internal vhosts

### ISSUE THREAD

**Issue by rbsec** [OWASP/wstg#791]
There are a couple of issues I've come across recently that I don't think are covered in the WSTG.

Firstly, lots of applications use a CDN (such a Cloudflare), which provides various protection such as a WAF. However, it's often possible to completely bypass the CDN/WAF by making requests directly to the webserver's IP address (rather than using the domain which points to the CDN). The basic steps would be:

1. Determine that a WAF/CDN is in use.
2. Identify the real IP address of the website (subdomain grinding, scanning the IP range of the client, internal IP leakage).
3. Make direct requests to the IP address (probably with a custom `Host` header or other means to override DNS).

I guess this would fall under 01 - Information Gathering? Does it justify it's own page, or is there an obvious place to include it in the existing ones?

---

Secondly, you can sometimes get an issue where a server has vhosts configured that do not have publicly resolvable domains. For example, you might have a server sitting on the corporate network that hosts both `www.example.org` (externally resolvable) and `admin.example.org` (only resolvable from the internal DNS servers). However, if you set a custom `Host` header (or override DNS), you can access `admin.example.org` from outside the network.

I guess this would fit best into 07-Input_Validation_Testing/17-Testing_for_Host_Header_Injection.md?

I'd be interested to hear your though @ThunderSon and @kingthorin (and anyone else).

**Comment by kingthorin** [comment]
For the second one I definitely agree on 07-17. For the first one I need to think on it a bit.

**Comment by ThunderSon** [comment]
For the first one, it's  2 parts:
1. Discovery phase, definitely part of understanding the tech being used and adding it to map
2. For the last step in your schema, I believe this fits properly with what you're discussing: https://github.com/OWASP/wstg/blob/ede0735edb3ac674137f2176ae5ff96e3d134bcd/document/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema.md#testing-for-special-request-header-handling

As for the second point in your proposal, it's good to add where you mentioned.

**Comment by rbsec** [comment]
@ThunderSon the [Map Application Architecture](https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/01-Information_Gathering/10-Map_Application_Architecture.md) page looks like it's been pretty much unchanged since it was imported, and is a bit of a wall of text.

I think it could do with breaking down into sections, and updating to add some newer areas (such as CDNs, cloud hosted WAFs, cloud components, etc). Are you happy for me to give it a cleanup at the same time?

**Comment by kingthorin** [comment]
I’m good with that plan.

**Comment by rbsec** [comment]
This was resolved in #795 and #796
