### ISSUE TITLE
Add content-security-policy generation tools

### ISSUE THREAD

**Issue by c0nrad** [OWASP/wstg#807]
**What would you like added?**
Briefly describe the topic of the new content. Is this a new section or an addition to an existing topic?

It would be nice to include some free tools for automatically generating Content Security Policies with best practices:
https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/02-Configuration_and_Deployment_Management_Testing/12-Test_for_Content_Security_Policy

Specifically the following chrome/firefox extension:
* Chrome Extension: https://chrome.google.com/webstore/detail/content-security-policy-c/ahlnecfloencbkpfnpljbojmjkfgnmdc
* Firefox Extension: https://addons.mozilla.org/en-US/firefox/addon/csp-generator/

A non-trivial number of developers have used them to generate CSP for their websites.

(Disclaimer, I am the owner of these tools, if this is not appropriate, no worries)

Would you like to be assigned to this issue?
Check the box if you will submit a PR to add the proposed content. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by rbsec** [comment]
I can see why these types of tools might be useful to developers - but I'm less clear on how you'd use them as part of a web application pentest?

**Comment by c0nrad** [comment]
Hi @rbsec, I imagined that they would go under the "Remediation" section on the page. So if someone has an insecure policy, they can use the tool to create a better one. This tool will never recommend any insecure directives (such as "unsafe-inline"), and follows best practices such as full-path on sensitive directives (script-src/object-src), default 'none', HTTP, etc.

**Comment by kingthorin** [comment]
There's normally a tools block at the end of each scenario as well. I assume if they tell you how to assemble of fix CSP that's handy for Pentesters to identify CSP misses and therefore potential weaknesses as well :wink:
