### ISSUE TITLE
Incorrect text "Chance Verification" in Typical_SDLC_Testing_Workflow.gif image in '3. The OWASP Testing Framework' section

### ISSUE THREAD

**Issue by amalyshkin** [OWASP/wstg#846]
**What's the issue?**
There is an image https://github.com/OWASP/wstg/blob/master/document/3-The_OWASP_Testing_Framework/images/Typical_SDLC_Testing_Workflow.gif in https://github.com/OWASP/wstg/blob/master/document/3-The_OWASP_Testing_Framework/0-The_Web_Security_Testing_Framework.md. The left bottom block (in 'Maintenance' section) in this image is named "Chan**C**e Verification". But the correct name should be "Chan**G**e Verification"

**How do we solve it?**
The image should be updated to change this text from "Chance Verification" to "Change Verification"

**Comment by kingthorin** [comment]
@jishnurippon could we get a touch-up on this?

https://github.com/OWASP/wstg/commit/268f2b7c4e06f2edad1e4ab9049a68446d730e13

**Comment by kingthorin** [comment]
@rejahrehim I believe he was a contact of yours. I see he hasn't been active on GitHub in quite a while so may not see that request for assistance.

**Comment by ThunderSon** [comment]
This was a really ... tricky find. Thank you for pointing this out @amalyshkin

**Comment by rejahrehim** [comment]
> @rejahrehim I believe he was a contact of yours. I see he hasn't been active on GitHub in quite a while so may not see that request for assistance.

I will  check this and update this issue.
