### ISSUE TITLE
E-commerce testing guide

### ISSUE THREAD

**Issue by rbsec** [OWASP/wstg#855]
When you have an e-commerce site, there are quite a lot of specific issues that you should check for (beyond the usual stuff), such as:

- Price tampering (on the site)
- Price tampering (on the handover to the payment gateway)
- Currency tampering
- Time-delayed requests for items with changing values
- Negative item quantities
- Test or debug payment cards
- Skipping the actual payment process
- Abusing discount codes (multiple use, guessing, wildcards, etc)
- Insecure handling of cardholder data

Some of these are (briefly) covered as examples in the Business Logic section of the guide, but several of them aren't - and where they are mentioned there's no real guidance on how to test them.

Do you think it's worth creating a specific page for testing e-commerce/payment functionality (probably within Business Logic)? Or trying to work out if some of these fit in the existing sections and expanding the guidance in them?

**Comment by kingthorin** [comment]
I'd say this definitely belongs in 4.10. Either beefing up the existing content or maybe as a level 5 page (like the various "flavors" of SQLi are currently).

**Comment by kingthorin** [comment]
Are you up for tackling this? Shall I assign you?

**Comment by ThunderSon** [comment]
@kingthorin I'm a bit worried about adding things to other BUSL tests.

I love the incoming work, I feel like it could be its own thing till we figure out a revamp for the whole section.
That section is mostly legacy, non-conformant with how the whole guide is.

What do you think?

**Comment by rbsec** [comment]
I think it probably makes sense in 4.10, but I'm not sure how easy it would be to merge into the existing files in there. Sections like [4.10.1](https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/10-Business_Logic_Testing/01-Test_Business_Logic_Data_Validation.md) are quite general (and in a slightly different format with just a few examples rather than any real testing steps).

Alternatively it could be a separate section (4.10.10, etc) - but then there would be a certain amount of overlap with the existing ones (such as 4.10.3 and 4.10.6).

**Comment by kingthorin** [comment]
Let's go 4.10.1.1 for now then?

**Comment by rbsec** [comment]
Are you thinking subsections of various bits in business logic (such a 4.10.1.1, 4.10.3.1, etc) for payment specific stuff? Because that'll probably be a lot of duplication, and it might be better to refresh the main business logic ones at the same time.

Or all the payment stuff together in one section (4.10.10)?

**Comment by ThunderSon** [comment]
I feel like just writing out the stuff you feel are needed is the top priority.

Let's give sectioning and the old section a look while you tackle down the payment BUSL.
I believe the content can always be moved around once written :)

Kick off a draft, and before we merge, we should have a plan set out to contain it.

**Comment by kingthorin** [comment]
No no, I was thinking all of this together as 4.10.1.1. But I've re-read the bullets, it's more than just data validation. So I'm good with 4.10.10.

**Comment by rbsec** [comment]
I've made an initial skeleton in #857  - any comments or feedback would be useful before I start fleshing it out.
