### ISSUE TITLE
backtick breaks the markdown

### ISSUE THREAD

**Issue by the-rend** [OWASP/wstg#878]
**What's the issue?**
there is an extra backtick [here](https://github.com/OWASP/wstg/blob/master/style_guide.md?plain=1#L183) that breaks the markdown.

**How do we solve it?**
remove the backtick kindly.

Would you like to be assigned to this issue?
sure, I put all the effort into this arduous task 😁
- [x] Assign me, please!

**Comment by kingthorin** [comment]
You don't need to create issues for things unless there's some concern that someone else might tackle the issue in the mean time.

**Comment by the-rend** [comment]
oh ok got it, I won't create issues for minor improvements in the future.

**Comment by the-rend** [comment]
should I close [the PR](https://github.com/OWASP/wstg/pull/879) for this issue?
