### ISSUE TITLE
Edit localStorage article to include other forms of insecure client-side storage

### ISSUE THREAD

**Issue by itscooper** [OWASP/wstg#9]
E.g. 
in the DOM as variables
WebSQL
etc

May require a rename... perhaps "Insecure Client-Side Storage of Sensitive Data"

**Comment by kingthorin** [comment]
Ref: https://www.owasp.org/index.php/Test_Local_Storage_(OTG-CLIENT-012)

**Comment by kgeorgiou** [comment]
May I pick this up? :)

**Comment by victoriadrake** [comment]
Assigned! Thank you @kgeorgiou!

**Comment by kingthorin** [comment]
@kgeorgiou it's been a month, any news on this?

**Comment by kgeorgiou** [comment]
Hey @kingthorin, you can check the progress on my [forked branch](https://github.com/kgeorgiou/wstg/blob/update-client-side-storage-document/document/4_Web_Application_Security_Testing/4.12_Client_Side_Testing/4.12.12_Testing_Web_Storage_OTG-CLIENT-012.md) - please let me know if you have any feedback so far.

If this is time-sensitive I can have a PR ready by Monday :)

**Comment by kingthorin** [comment]
Thanks, there isn't a particular rush. I just wanted to make sure it was in progress.
