### ISSUE TITLE
XLS Checklist has broken validation on Status column

### ISSUE THREAD

**Issue by ivanseidel** [OWASP/wstg#923]
**What's the issue?**
The Excel Checklist version has a broken validation on the status column, causing it to present error and not autocomplete correcly

**How do we solve it?**
Fix the autocomplete reference

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by kingthorin** [comment]
Done in OWASP/wstg#924
