### ISSUE TITLE
Automatically generate XLS/ODT

### ISSUE THREAD

**Issue by ivanseidel** [OWASP/wstg#925]
**What would you like to happen?**
An XLSX to be generated automatically based on the JSON Checklist

**Comment by kingthorin** [comment]
See discussion in: https://github.com/OWASP/wstg/pull/924

**Comment by ivanseidel** [comment]
I spent a few hours looking into XLS manipulation libraries, and got a bit disapointed with their limitations in formating and copying data. Both Python libraries lack a way of copying from a template, and using validations/formating.

**Comment by kingthorin** [comment]
Is there a good way to do it with power shell? It’s more Microsofty 😉

**Comment by ivanseidel** [comment]
Just finished... Check it out, this was built from the JSON file
[WSTG-Checklist_v4.2.xlsx](https://github.com/OWASP/wstg/files/8457803/WSTG-Checklist_v4.2.xlsx)
