### ISSUE TITLE
WSTG-CONF-12 should mention the unsafe-hashes CSP directive

### ISSUE THREAD

**Issue by Loqova** [OWASP/wstg#935]
**What would you like added?**
WSTG-CONF-12 should mention the insecure configuration of CSP when using the `unsafe-hashes` directive too. See: https://content-security-policy.com/unsafe-hashes/.

**Would you like to be assigned to this issue?**
Check the box if you will submit a PR to add the proposed content. Please read CONTRIBUTING.md.
- [ ] Assign me, please!

**Comment by manindar-mohan** [comment]
I would like to contribute, can you assign me.

**Comment by kingthorin** [comment]
Absolutely! :grinning:
