### ISSUE TITLE
Simple typo fix

### ISSUE THREAD

**Issue by Barroqueiro** [OWASP/wstg#980]
**What's the issue?**
Simple typo in WSTG-SESS-10's description

**How do we solve it?**
Just remove the seconds are.

Would you like to be assigned to this issue?
Check the box if you will submit a PR to fix this issue. Please read CONTRIBUTING.md.
- [x] Assign me, please!

**Comment by rbsec** [comment]
Good spot - thanks for submitting this. For simple stuff like this, feel free just to open a direct PR without an associated issue - there's nothing that we'd really need to discuss just to fix a typo.
