### ISSUE TITLE
Translation into Russian

### ISSUE THREAD

**Issue by andrettv** [OWASP/wstg#989]
Hi, 
Translation is on my page https://github.com/andrettv/WSTG/tree/master/WSTG-ru. 
I've forked the latest branch at the end of July 2022. 
Can you help me properly move it further (check its structure, produce pdf, make it visible on the project page, etc.)?

**Comment by kingthorin** [comment]
@andrettv thanks for tackling this.

The repo seems to be a combination of this repo and the web repo, but structurally it seems fine I guess.
As for building the PDF we have that done by a github action so take a look in the .github folder. I have no idea if any of the regexes etc will have problems with non-English content. I'll put together some PRs to lilnk your repo.

**Comment by kingthorin** [comment]
FYI, this hasn’t been forgotten 😉

**Comment by andrettv** [comment]
I want to add new (MFA) scenario to my translation. Is it still possible on that stage and if yes I need an advice how to discover and merge new additions to future v5.0 further?

**Comment by kingthorin** [comment]
You can add/adapt any content at any time there’s no specific requirement from this side.

As for identifying and adding content I guess you’d need to keep an eye on PRs for this repo and work from those.
